version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/roomatch
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
